---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-app.demo
  namespace: counter-app
spec:
  ingressClassName: nginx
  rules:
  - host: argocd-app.demo
    http:
      paths:
      - backend:
          service:
            name: counter-service
            port:
              number: 80
        path: /argocd-app
        pathType: Prefix
